### ISSUE TITLE
Git Reource

### ISSUE THREAD

**Issue by arkhan** [NicolasPetton/pass#12]
Hello,

Melpa is taking the changes from github or https://petton.fr/git/nico/pass

Thanks

**Comment by DamienCassou** [comment]
On March 7, 2017 4:19:02 PM GMT+01:00, "Edison Ibañez" <notifications@github.com> wrote:
>Melpa is taking the changes from github or
>https://petton.fr/git/nico/pass

Github:
https://github.com/melpa/melpa/blob/master/recipes/pass
-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by NicolasPetton** [comment]
Edison Ibañez <notifications@github.com> writes:

> Hello,

Hi,

> Melpa is taking the changes from github or
> https://petton.fr/git/nico/pass

GitHub, indeed, but the changes from https://petton.fr/git/nico/pass are
replicated on GitHub as well.

Cheers,
Nico
