### ISSUE TITLE
k on directory removes the previous entry instead of the directory

### ISSUE THREAD

**Issue by thblt** [NicolasPetton/pass#14]
When pressing k on a directory, pass removes the previous entry instead of the directory.  

Eg, if you have:

```
.password-store
├── reddit.com
├── special [point here]
    ├── test
```

press k, then y, the reddit.com entry gets deleted.  

I'd expect pass to either:

 1. Recursively delete the directory, maybe requiring a "full" confirmation (`yes-or-no-p`)
 2. Refuse to do anything.

Thanks

**Comment by NicolasPetton** [comment]
I went for the simplest solution (not doing anything).
