### ISSUE TITLE
First entry gets indented twice

### ISSUE THREAD

**Issue by thblt** [NicolasPetton/pass#15]
The very first entry of the store (not of subfolders) is displayed with two `├──`, eg:

```
.password-store
├── ├── aaa.com
├── abc.com
```

Thanks!

**Comment by NicolasPetton** [comment]
Can you show me (an anonymized subset of) what `ls ~/.password-store` looks like?

**Comment by thblt** [comment]
> Can you show me (an anonymized subset of) what `ls ~/.password-store` looks like?

After trying a bit more, it seems that the presence of a `.git` folder triggers the bug.   Here's [an example repo](https://github.com/thblt/passbug) which you can clone as .password-store, `M-x pass` should show the double indent.  But any *git-versioned* repo should work

**Comment by NicolasPetton** [comment]
Commit 22b324b should fix the issue.

**Comment by thblt** [comment]
Works for me, thanks!
