### ISSUE TITLE
After M-x pass, pass--tree shows wrong type argument listp

### ISSUE THREAD

**Issue by ninrod** [NicolasPetton/pass#16]
Hi Nicolas.

I've just installed your package, but after `M-x pass`, I get this:

pass--tree: Wrong type argument: listp, "email/sec/myscretemail"

**Comment by NicolasPetton** [comment]
Filipe Silva <notifications@github.com> writes:

> pass--tree: Wrong type argument: listp, "email/sec/myscretemail"

Which version are you using? Commit 2ccf4f6 should fix it.

**Comment by ninrod** [comment]
Hum ok. must be it. I refresh my melpa local cache and test again.

**Comment by ninrod** [comment]
it worked! tks
