### ISSUE TITLE
support for multiline insert

### ISSUE THREAD

**Issue by ninrod** [NicolasPetton/pass#17]
Is there a way to insert a multiline pass entry?

I can do that in the terminal with `pass insert -m my/secret/file.txt`.

**Comment by NicolasPetton** [comment]
No, there is currently not, but I will implement it.

**Comment by NicolasPetton** [comment]
It looks like password-store.el doesn't support it. Isn't visiting the file enough?

**Comment by ninrod** [comment]
Hum, Yeah, it does not. I think this should be supported straight from `pass` itself. 
it seems that `pass insert -m` just opens a `heredoc` in the terminal. I don't know if elisp can connect to that. 

I don't think I understand what you mean by "visiting the file". My idea would be creating a `pass-insert-multiline` function that would `find-file` a new buffer for the user.

**Comment by NicolasPetton** [comment]
Filipe Silva <notifications@github.com> writes:

> I don't think I understand what you mean by "visiting the file". My
> idea would be creating a `pass-insert-multiline` function that would
> `find-file` a new buffer for the user.

That's exactly what I was thinking about :)

**Comment by ninrod** [comment]
Allright. So `pass insert -m path/to/my/password` really just opens a `cat` like terminal space so that user can enter text. Can elisp connect to this thing? Or do we have to open a feature request upstream so that this is supported?

**Comment by NicolasPetton** [comment]
You can try `C-u i` in your password-store buffer.

**Comment by ninrod** [comment]
fantastic. will test as soon as this lands to melpa.

**Comment by ninrod** [comment]
yep, working. I'd like it to integrate with git though.

**Comment by ninrod** [comment]
nevermid, I see that we have already an issue open for this: #8
