### ISSUE TITLE
Evil keybindings

### ISSUE THREAD

**Issue by academikuser** [NicolasPetton/pass#19]
After M-x pass v to view instead 

`v runs the command evil-visual-char`

**Comment by NicolasPetton** [comment]
You can press `RET` instead, is that good enough?

**Comment by academikuser** [comment]
`RET` is going to the next line.  
`w` isn't copying, 
it's jumping ahead to the start of the next word.

**Comment by NicolasPetton** [comment]
academikuser <notifications@github.com> writes:

> `RET` is going to the next line.  
> `w` isn't copying, 
> it's jumping ahead to the start of the next word.

I'm not an EVIL user, so I'm not sure what to do about this.

**Comment by academikuser** [comment]
Won't be able to submit a pull request with evil keybindings for 8 weeks or so.
