### ISSUE TITLE
OTP management extension proposal

### ISSUE THREAD

**Issue by volrath** [NicolasPetton/pass#22]
Hello @NicolasPetton,

Over the weekend I made a customization I wanted to have in the `pass` major mode, to be able to handle OTP/2FA directly from Emacs. It looks like this:

![pass-otp](https://user-images.githubusercontent.com/39625/30051394-2a7c956c-9222-11e7-9458-8343b9449fde.gif)

(I realize the gif might be a bit fast, but I think it transmit the whole idea)

I thought it might be useful for other people and could be contributed to this repo.
The reason I'm opening an issue instead of a PR is because my implementation depends on the [`pass-otp`](https://github.com/tadfisher/pass-otp) extension for [`pass`](http://passwordstore.org/), and so the features shown in the gif wouldn't work on a freshly install of `pass`.

Now, TBH, this is the first time I'm tinkering with an Emacs major mode, so maybe there are ways to handle these OTP features as a minor mode or something like that, or a graceful way to add it to the `pass` major mode with those features shut down if the user don't have `pass-otp` installed. But I am more than willing to collaborate if you see this as a useful thing to have inside `pass`.

If you want to check out the code: https://github.com/NicolasPetton/pass/compare/master...volrath:master, you will notice there are some `password-store-otp-*` functions, those are part of another library I made: [`password-store-otp`](https://github.com/volrath/password-store-otp.el), which is now [awaiting for approval in melpa](https://github.com/melpa/melpa/pull/4983)

If you want to try it out, you just need to load `password-store-otp.el` and my fork of `pass.el` into your Emacs, and of course have `pass-otp` installed.

**Comment by NicolasPetton** [comment]
Hi @volrath,

I'll definitely review your code, thanks!

/cc @DamienCassou, who uses OTP/2FA IIRC.

**Comment by DamienCassou** [comment]
Hi @volrath. Could you please tell us about one or more user stories that would make use of this feature? I'm not familiar with OTP, even less with pass-otp. The only thing I know is that I can use FreeOTP or Google Authenticator on my Android phone to activate 2FA in Gitlab and Github. Your answer might make me understand your gif.

**Comment by volrath** [comment]
Hey @DamienCassou,

So, my most common story is the same as what you describe as your regular use case for 2FA. I use Google Authenticator or Authy to scan a 2FA QR Code and that application will give me OTP tokens (six digits)

I've been enabling 2FA in more and more accounts, every work related aws, google, gitlab, slack account I have, and it has gotten a bit tedious to have my auth information scattered between my computer (pass) and my phone (google authenticator,) so I wanted to centralize it all in Emacs.

There are two things I usually do when I enable 2FA for any account:

1. I scan the QR code they provide with my phone, which basically gives you a `otpauth://` URI that's used to generated time based tokens.
2. I save the recovery codes they provide and also take a screenshot of the QR code, in case I lose my phone (I don't like using cloud based backups that things like Authy provide)

So last week I found `pass-otp`, a `pass` extension that helps saving OTP URIs into entries, and I did a [elisp library to be able to interact with it from emacs](https://github.com/volrath/password-store-otp.el). Think of it as what `password-store.el` is to `pass`.

Next I wanted to be able to use the `pass.el` major mode (since I love it, haha) so I did this extension.

In this extension I also included something that `pass-otp` doesn't have, which is the ability to get a OTP URI from a screenshot, so I don't have to scan the QR code in my phone, and then type the URI that it gives me into `pass`.

My most common use cases are:

1. I would activate 2FA in any account, and when presented with a QR code, I would save the OTP URI to a `pass` entry by taking a screenshot of it (`o s` in `pass` major mode). This will append the OTP URI to a certain entry.
2. I would also save it into my phone (just in case)
3. When login into a 2FA protected account, I would go to my `pass` major mode, copy the password for the account (`w`) and then copy the current OTP token into my clip board (`o t`).
4. log in =)

Besides that, I provided features to reproduce a QR code from an entry, in case you want to scan it again on a new phone, or something like that. And every time you enter `pass-view-mode` for an entry that has a OTP URI attached to it, you would see the token and the expiration time for that URI instead of the actual URI, kind of the same as Google Authenticator interface.

I hope this clarifies things, let me know if I can explain something better.

P.D. @NicolasPetton thanks! but beware, I don't think the code is ready to be used IRL yet. I still have some work to do on it if it's going to be used by more people. I just wanted to start by asking you guys if you thought it might be useful and worth integrating it.

**Comment by DamienCassou** [comment]
This looks amazing and certainly something I would like to use.

**Comment by NicolasPetton** [comment]
I really like what you did. That's something I'd really like to get into pass. Or it could be a plugin, if you think it shouldn't be in pass itself.

**Comment by volrath** [comment]
The only thing that made me doubt about adding it directly to `pass` was that I don't know what's the best way to handle when the user doesn't have `pass-otp` installed, UX wise.

I guess in order to check if the user has `pass-otp` installed, we could just look if `/usr/lib/password-store/otp.bash` or `~/.password-store/otp.bash` exists (According to https://www.passwordstore.org/#extensions) But I'm not entirely sure this covers all the possible scenarios.

The "importing URIs from screenshots" feature depends on [`zbar`](http://zbar.sourceforge.net/), so we would have to check for that too.

I think if we handle these two cases gracefully, we can add it to `pass` and enable the features if the user's system meets the requirements (and if not, maybe just `message` a warning when the user tries to use them.) So that the new OTP requirements are just "soft requirements" to use `pass`.

If that sounds good to you, I'll open a PR and start working on it.

**Comment by DamienCassou** [comment]
Daniel Barreto <notifications@github.com> writes:
> The only thing that made me doubt about adding it directly to `pass`
> was that I don't know what's the best way to handle when the user
> doesn't have `pass-otp` installed, UX wise.


what about displaying an error message when the user first tries
pass-otp? Currently, executing

    (password-store--run "otp" "uri" entry)

will throw "Error: otp is not in the password store". This is not the
perfect error message, but I guess it is good enough for a first
version.


> I guess in order to check if the user has `pass-otp` installed, we
> could just look if `/usr/lib/password-store/otp.bash` or
> `~/.password-store/otp.bash` exists (According to
> https://www.passwordstore.org/#extensions) But I'm not entirely sure
> this covers all the possible scenarios.


this looks a bit complex and unreliable (what about macOS?). 


> The "importing URIs from screenshots" feature depends on
> [`zbar`](http://zbar.sourceforge.net/),


this hasn't been updated for ages so I'm a bit suspicious.


> so we would have to check for that too.


Again, you could check the binary you need exists at the time the user
actually needs it.


> I think if we handle these two cases gracefully, we can add it to
> `pass` and enable the features if the user's system meets the
> requirements (and if not, maybe just `message` a warning when the user
> tries to use them.) So that the new OTP requirements are just "soft
> requirements" to use `pass`.


or add a pass-otp-enable configuration option to that the user gets
error messages if requirements are not satisfied.

> If that sounds good to you, I'll open a PR and start working on it.


Please go ahead.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by NicolasPetton** [comment]
@volrath 👍

**Comment by mdorman** [comment]
If this is merged, should the issue be closed?

**Comment by NicolasPetton** [comment]
Definitely!
