### ISSUE TITLE
Deadlock in pass-copy when using exwm

### ISSUE THREAD

**Issue by ieure** [NicolasPetton/pass#25]
If you use exwm and pass, pressing `w` to copy a password deadlocks Emacs if the password isn't already in gpg-agent.  The copy operation blocks Emacs, which prevents exwm from creating the window for pinentry.  If you hit `C-g`, the blocking operation aborts, the pinentry window appears, and you can enter the password.  Hitting `w` again will put the password into the kill-ring.

Correcting this probably requires changes to password-store, adding a function which calls `pass` asynchronously, and updating pass.el to use that.

**Comment by drej2k** [comment]
I too run exwm and emacs within the tiled windows manager. 
I have the same problem, I cannot use w to copy a password. 
However, everything else works. 
The pass phrase prompt is asked in the emacs mode line and not via a popup gui like you are describing. 
I previously had the same issue with the popup gui timing out or having to wait for ages until it showed the gui that allowed one to enter their passphrase. But I overcame this issue by tweaking my setup and it is no longer the case...

Here are the steps that work for me:
1. Open pass: M-x pass
2. A buffer with a list of all my passwords is shown: - hit enter on one
3. In the emacs mode line it prompts to enter my pass phrase - I enter my pass phrase
4. After successfully entering the pass phrase the details are shown with the password hidden
5. I highlight and copy the password (in the hidden form)  and it is copied to the kill-ring  - (M-w)
**I did change the setup slightly to achieve this however i still need to get copy (w) working...

##### NOTES: 
1. Even once I have unlocked I cannot highlight an item in the list and hit w to copy the password, i get the following error:
    password-store--run: gpg-agent[9025]: /home/andre/.gnupg/gpg-agent.conf:4: invalid option
    gpg: can’t connect to the agent: End of file
    gpg: problem with the agent: No agent running
    gpg: decryption failed: No secret keyErr
2. Similarly I cannot open pass (M-x pass), select a list item and hit w to get it to unlock (ask for the passphrase) and have pass automatically copy the password to the kill ring...

@ieure have you made progress on this? Is this where you are currently at?

**Comment by ieure** [comment]
I haven't done anything. I have fairly limited time to contribute to things these days, so I generally don't contribute patches unless the maintainer is +1 on my approach.  Since I haven't heard anything back at all, I haven't done any work to fix it.

**Comment by drej2k** [comment]
@ieure Fair enough.

**Comment by mraruiz** [comment]
The following advice fixed the issue for me (I use pinentry-emacs):
(defun my-password-store-copy (oldfun &rest args)
  (interactive (list (password-store--completing-read)))
  (let ((entry (car args)))
    (async-start `(lambda ()
                    (add-to-list 'load-path ,(file-name-directory (locate-library "dash")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "with-editor")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "s")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "f")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "password-store")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "password-store-otp")))
                    (require 'password-store)
                    (password-store-get ,entry))
                 `(lambda (password)
                   (password-store-clear)
                   (kill-new password)
                   (setq password-store-kill-ring-pointer kill-ring-yank-pointer)
                   (message "Copied %s to the kill ring. Will clear in %s seconds." ,entry (password-store-timeout))
                   (setq password-store-timeout-timer
                         (run-at-time (password-store-timeout) nil 'password-store-clear))))))

(advice-add #'password-store-copy :around #'my-password-store-copy)

As starting a new process expensive, I suppose the above function is only useful for others experiencing hanging with EXWM.

**Comment by mraruiz** [comment]
The following advice for password-store fixed this issue for me:
```emacs-lisp
(defun my-password-store-copy (oldfun &rest args)
  (interactive (list (password-store--completing-read)))
  (let ((entry (car args)))
    (async-start `(lambda ()
                    (add-to-list 'load-path ,(file-name-directory (locate-library "dash")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "with-editor")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "s")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "f")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "password-store")))
                    (add-to-list 'load-path ,(file-name-directory (locate-library "password-store-otp")))
                    (require 'password-store)
                    (password-store-get ,entry))
                 `(lambda (password)
                   (password-store-clear)
                   (kill-new password)
                   (setq password-store-kill-ring-pointer kill-ring-yank-pointer)
                   (message "Copied %s to the kill ring. Will clear in %s seconds." ,entry (password-store-timeout))
                   (setq password-store-timeout-timer
                         (run-at-time (password-store-timeout) nil 'password-store-clear))))))

(advice-add #'password-store-copy :around #'my-password-store-copy)
```
Considering that starting a new process is expensive, I don't see why this advice would be useful outside of this particular issue.

**Comment by NicolasPetton** [comment]
@ieure I would definitely accept a patch that uses async functions.

**Comment by ieure** [comment]
Ugh, that was made on the wrong repo.  I'll PR the correct one shortly.

**Comment by ieure** [comment]
Okay, patch is, I think, finally where it needs to be: https://lists.zx2c4.com/pipermail/password-store/2019-January/003518.html

**Comment by DamienCassou** [comment]
awesome work @ieure ! And thanks for the detailed commit message in password-store repository.

**Comment by ieure** [comment]
This is working for me with recent password-store versions.
