### ISSUE TITLE
Syntax highlight broken by double quotes

### ISSUE THREAD

**Issue by marcocen** [NicolasPetton/pass#26]
When a saved password has an unclosed double quote("), the syntax highlighting on successive lines doesn't work until that double quote is closed.
```
foobar
Username: baz
```
Highlights "Username:"

But 
```
foo"bar
Username: baz
```
Leaves the second line decorated as a string.

**Comment by NicolasPetton** [comment]
Thanks, the fix in master should resolve the issue.
