### ISSUE TITLE
Can't reach "Enter contents of test and press Ctrl+D when finished:" buffer

### ISSUE THREAD

**Issue by dingesista** [NicolasPetton/pass#27]
Hi

Using Debian pass 1.7.3.1 (unstable) and Debian emacs-snapshot (or  Debian Emacs25.2.2) when entering a password, I see this in the minibuffer:

"Enter contents of test and press Ctrl+D when finished:"

However, I am not able to enter any content in the minibuffer, or another. Any key (including Ctrl+D) will create the password. I can edit it after.

**Comment by NicolasPetton** [comment]
It looks like a message from calling `pass`, I'll investigate.

**Comment by calancha** [comment]
That was a residual message coming from `password-store-insert' (called by `pass-insert').
It has been fixed in password-store.el v2.0.5.
Now you must see the following message instead:
"Successfully inserted entry for test"

**Comment by NicolasPetton** [comment]
Thanks, closing.
