### ISSUE TITLE
Updates needed for more recent password-store.el versions

### ISSUE THREAD

**Issue by kamidon** [NicolasPetton/pass#28]
I'm seeing some regressions in functionality with recent versions of `password-store.el`. Most importantly, because `password-store-edit` from `password-store.el` always works on a temporary file in shared memory instead of just opening the file in the `~/.password-store/` directory, `pass-view` from `pass.el` results in a `text-mode` buffer instead of a `pass-view-mode` buffer. Furthermore, `password-store.el` seems to always conclude that it needs to create a git commit even when nothing has been changed in the entry, which clutters up the git history with useless commits when you just want to view some of the added fields other than the password.

I was thinking of fixing this by making `pass-view` just open the file from `~/.password-store` directly, but having it set to be read-only and having the keybinding to toggle read-only mode switch to calling `password-store-edit` from `.password-store.el`. Does that sound like a reasonable approach?

**Comment by NicolasPetton** [comment]
Keith Amidon <notifications@github.com> writes:

Hi!

> I'm seeing some regressions in functionality with recent versions of
> `password-store.el`. Most importantly, because `password-store-edit`
> from `password-store.el` always works on a temporary file in shared
> memory instead of just opening the file in the `~/.password-store/`
> directory, `pass-view` from `pass.el` results in a `text-mode` buffer
> instead of a `pass-view-mode` buffer. Furthermore, `password-store.el`
> seems to always conclude that it needs to create a git commit even
> when nothing has been changed in the entry, which clutters up the git
> history with useless commits when you just want to view some of the
> added fields other than the password.

I have password-store v20181031.1440 from MELPA installed, and I use
`pass-view` without reproducing your issue.

Which version do you use?

**Comment by kamidon** [comment]
Sorry for the rather delayed reply. Holidays and work consumed all my free time the past month.

I'm using the current melpa-stable versions of pass (1.7) and password-store (1.7.3). Maybe it is just these that are incompatible?

**Comment by NicolasPetton** [comment]
Keith Amidon <notifications@github.com> writes:

> Sorry for the rather delayed reply. Holidays and work consumed all my free time the past month.
>
> I'm using the current melpa-stable versions of pass (1.7) and
> password-store (1.7.3). Maybe it is just these that are incompatible?

The latest release of pass.el is v1.8, which works well with
password-storer 1.7.3.

I just saw that it is not on melpa stable though, I'm going to
investigate.

**Comment by NicolasPetton** [comment]
Nicolas Petton <nicolas@petton.fr> writes:

> I just saw that it is not on melpa stable though, I'm going to
> investigate.

The reason was a missing git tag.
You can either use pass.el from Melpa, or wait for the next build of Melpa stable.

**Comment by kamidon** [comment]
The update to melpa-stable did indeed resolve the problems I was having. Thanks!
