### ISSUE TITLE
Add a binding to copy login

### ISSUE THREAD

**Issue by vincentbernat** [NicolasPetton/pass#29]
Hey!

`pass` is lacking a way to easily copy a login in the clipboard. Usually, the login is stored on a line starting with `login: `. It would be very convenient to be able to copy it with one keypress. Would such a feature be accepted? If yes, I can try to implement it.

**Comment by calancha** [comment]
Hi, that's a nice suggestion!
I got a similar idea while using this library during the last few months.
I've have started last week to work on this issue and I am now cleaning up the patch; I expect to share it soon.

**Comment by calancha** [comment]
OK, we have now a trailer of the incoming pull request:
https://www.youtube.com/watch?v=NbNY0FzXEwU

Hopefully, the new feature will arrive by next week: I'm not much worry about Frieza, but you know, Cell requires a bit more of kamehamehas ;-)

**Comment by NicolasPetton** [comment]
Trailers for pull requests, I love the concept.

**Comment by calancha** [comment]
Indeed, the full movie was world wide released a few weeks ago: https://www.youtube.com/watch?v=whG9uPp0eto
[There are rumors that Vegeta might be nominated for an Oscar!]

The point with this feature is that requires changes in password-store.el.  I have submitted recently a couple of patches there to test how they are responding (other things not related with this feature).  In fact, nobody is pushing in that project for 1 month ago; maybe they are on vacation.

I prefer to wait until password-store people be back before requesting the required changes to make this feature work as in the movie.

**Comment by calancha** [comment]
Finally, I have become the maintainer of password-store.el, thus it must be easier to add this feature.
See PR https://github.com/NicolasPetton/pass/pull/38

**Comment by NicolasPetton** [comment]
It's in master, so I'm closing this.
