### ISSUE TITLE
Font locking disappear when using swiper

### ISSUE THREAD

**Issue by vincentbernat** [NicolasPetton/pass#30]
Hey!

If I use swiper (a replacement for isearch built on top of Ivy), colors disappear for the `*Password-Store*` buffer. It's the first time I get something like this. The buffer is built by using `add-text-properties`. Maybe @abo-abo would have an hint on why this is happening?

**Comment by DamienCassou** [comment]
Hi @vincentbernat. Please update ivy to the latest git version and try again.

**Comment by vincentbernat** [comment]
It works fine now! Thanks!
