### ISSUE TITLE
URL specification

### ISSUE THREAD

**Issue by micah** [NicolasPetton/pass#39]
I see that if you include 'username' in the password file, pass will be able to find that value and make it available.

I also see that there is a URL functionality in pass, but I dont see how to specify that in the password file so it will be used properly. It doesn't seem to be a configuration option, like the username one is.

**Comment by NicolasPetton** [comment]
@calancha should know.

**Comment by calancha** [comment]
Sorry for the late response @micah,
Lib pass.el is built on top of password-store.el.  At pass.el we have the 2 commands handling with URLs:

1. pass-copy-url: To put in the kill ring the stored URL of the pass entry at point.

2. pass-browse-url: To navigate w/ your default browser to the stored URL of the pass entry at point.

You can consider 1. a sort of wrapper of `password-store-copy-field` and 2. a wrapper of `password-store-url`.  They both rely on the user option **password-store-url-field**; this is the option you are looking for to customize how you prefix the URLs in your pass entries.

**Comment by micah** [comment]
Tino Calancha <notifications@github.com> writes:

> You can consider 1. a sort of wrapper of `password-store-copy-field`
> and 2. a wrapper of `password-store-url`.  They both rely on the user
> option **password-store-url-field**; this is the option you are
> looking for to customize how you prefix the URLs in your pass entries.

Thanks for the reply, but I do not find **password-store-url-field** as
a customize variable. M-x customize-apropos also cannot find anything
under `password-store`

**Comment by calancha** [comment]
@micah I see... I guess you have installed pass.el 'by hand' from Github.  The recommended
way is to install packages using the built-in package.el; that way ensures all the dependencies are installed.

;; I have customized `package-archives` user option as follows (that is with ELPA and MELPA):
```
M-: package-archives RET
(("melpa" . "https://melpa.org/packages/")
 ("gnu" . "https://elpa.gnu.org/packages/"))
```

;; Then, you call
`M-x package-list-packages RET`

;; And install pass from the *Packages* buffer.  You will get automatically the latest password-store

**Comment by doolio** [comment]
@DamienCassou I think this issue could be closed.

**Comment by DamienCassou** [comment]
Good idea @doolio. Thank you for taking care of the project.
