### ISSUE TITLE
autoloading seems broken...

### ISSUE THREAD

**Issue by mdorman** [NicolasPetton/pass#4]
I have installed pass through melpa.  It is awesome---I spent a couple of hours today organizing 15 years worth of accumulated passwords, getting rid of passwords for services that no longer exist, categorizing others.  It was wonderful.

However, it only works if I actually `(require 'pass)`---if I rely on the package infrastructure, although the `pass` function is available because of its autoload, it fails because the things it wants to use aren't available.

I am sufficiently ignorant of many of these mechanisms that I don't actually know what should be done to resolve it.  I'll do some research and see if I can figure it out, but on the offhand chance that you already know, I thought I'd go ahead and report the issue in advance of having a patch.

**Comment by DamienCassou** [comment]
Could you please give us the error message you face?

**Comment by mdorman** [comment]
If I start a fresh emacs, do `M-x toggle-debug-on-error` and `M-x pass`, I don't get any error message at all.  I simply get an empty `*Password-Store*` buffer.  `*Messages*` includes:

    Debug on Error enabled globally
    pass-display-data: Buffer is read-only: #<buffer *Password-Store*>

That's it.

**Comment by DamienCassou** [comment]
How can I reproduce your error?

**Comment by eqyiel** [comment]
@DamienCassou I can reproduce it.

Move your `.emacs.d` and eval this from `emacs -Q`:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)
(package-install 'pass)
(pass)
;; *Messages* shows:
;; pass-display-data: Buffer is read-only: #<buffer *Password-Store*>
```
It works as expected if I explicitly `(load-file "~/.emacs.d/elpa/pass-20150624.1205/pass.el")`.

**Comment by DamienCassou** [comment]
Please try again with this new version and reopen if it does not fix your problem.

**Comment by mdorman** [comment]
Works beautifully.
