### ISSUE TITLE
Some keybindings do not work if GPG keys stored in a removeable device

### ISSUE THREAD

**Issue by doolio** [NicolasPetton/pass#41]
This may well be an issue with password-store.el (@calancha) and/or auth-store-pass.el (@DamienCassou). I store my keys offline in a removeable device specifically a [Trezor model T](https://wiki.trezor.io/GPG) hardware wallet.  So everytime I need to decrypt a password store gpg file to perform specific `pass` major-mode actions I have to confirm I want to decrypt the file on the trezor device.

- The `j`, `n`, `p`, `M-n`, `M-p`, `r`, `s` and `?` bindings work as expected without having to interact with the Trezor (which does not surprise me).
- The `U` binding works and requires confirmation on the Trezor as I would expect.
- The `k` binding works, does not require confirmation on the Trezor (which does not surprise me) but causes Emacs to hang for 1-2 mins. Once Emacs is responsive again the `g` binding works to refresh the `*Password-Store*` buffer removing the just deleted entry.
- The `i` binding works and does not require confirmation on the Trezor (maybe not a surprise).
- The `I` binding works and does not require confirmation on the Trezor (maybe not a surprise). 
- The `<RET>` binding works, requires confirmation on the Trezor (which does not surprise me) but I observe the following error in the `*Messages*` buffer which I don't understand which I also see whenever I try to view a password with `C-c C-c`:
```
Error during redisplay: (jit-lock-function 1) signaled (invalid-function #<subr quote>)
```
- The `w`(1), `b`(2), `u`(2), `f`(3) bindings **do not work** for me, request confirmation (as given by the number in the brackets that follows each binding) on the Trezor which surprises me as I would have only expected confirmation only once and result in the following error (not sure why the message is posted twice) in the `*Messages*` buffer:
```
Decrypting /home/doolio/.password-store/testdir/test.gpg...done
error in process sentinel: password-store: exited abnormally with code 2

error in process sentinel: password-store: exited abnormally with code 2
```
- I did not test the `o` binding beyond displaying the sub-menu.

I use EXWM too so it may be similar to #25.

FWIW, I'm using the following versions of these packages:
```
 ("auth-password-store" . "ff4940c647786914b3cbef69103d96a4ea334111")
 ("pass" . "919d8e3826d556433ab67d4ee21a509d209d1baa")
 ("password-store" . "98193d3bbb3538eda457d0db4ccccbcc4b04ce3d")
```
Thanks for your time.

**Comment by doolio** [comment]
I was able to get these bindings to work by changing the following switches in the trezor specific `agent-program` ~/.gnupg/trezor/run-agent.sh

`--pin-entry-binding=pinentry-emacs`
`--passphrase-entry-binary=pinentry-emacs`

I still observe the following error as described above.

`Error during redisplay: (jit-lock-function 1) signaled (invalid-function #<subr quote>)`

I still have some other issues but I believe they are related to the trezor-agent.

**Comment by cjauvin** [comment]
I do not use any removable device and I'm also having the `Error during redisplay: (jit-lock-function 12) signaled (invalid-function #<subr quote>)` error, which prevents me from inserting any new password. I'm using Emacs 27, are you also, by any chance?

**Comment by doolio** [comment]
Yes, I recently upgraded to 27.1 and still see this error.
