### ISSUE TITLE
Add optional arguments to pass-insert-generated function

### ISSUE THREAD

**Issue by fernandodemorais-jf** [NicolasPetton/pass#44]
Hello,

Please, consider the implementation of a function like `pass-insert-generated`, but with the possibility to pass, interactively, optional arguments of `password-store--run-generate` internal function, such as `password-length` and `no-symbols`.

It could be a new function, like `pass-insert-generated-with-options`, assigned to another keybinding.

I would love to make this suggestion through a Pull request, but my skills with EmacsLisp are still very limited.

Thanks in advance.

**Comment by doolio** [comment]
The latest version of `password-store.el` has `password-store-generate-no-symbols` and which allows you to specify the `password-length`. It is not exposed by `pass.el` though so you would need to `M-x password-store-generate-no-symbols` to use it.

**Comment by fernandodemorais-jf** [comment]
Thank you, @doolio!

**Comment by doolio** [comment]
You're welcome.
