### ISSUE TITLE
Undo can reveal the password

### ISSUE THREAD

**Issue by jthulhu** [NicolasPetton/pass#49]
When editing a password, doing undo twice right away reveals the password. This may lead to unwanted password leakage, by pressing undo many times to get to the original state.

**Comment by doolio** [comment]
Can you provide steps to reproduce this bug?

**Comment by doolio** [comment]
OK, I've submitted PR #60 which fixes this issue but it may be too extreme as you will  not be able to undo other changes in the buffer that you may want to.
