### ISSUE TITLE
[PATCH] Define face for key bindings

### ISSUE THREAD

**Issue by protesilaos** [NicolasPetton/pass#51]
Bonjour!  I noticed that key bindings are hardcoded to the `font-lock-constant-face`.  Do you think it is acceptable to have a named faced instead?

Please see the following patch (I can use the pull request system, if you prefer it).

```patch
From 304da54c95be596ed8fc7a58864dae520b1def76 Mon Sep 17 00:00:00 2001
Message-Id: <304da54c95be596ed8fc7a58864dae520b1def76.1645688334.git.info@protesilaos.com>
From: Protesilaos Stavrou <info@protesilaos.com>
Date: Thu, 24 Feb 2022 09:38:41 +0200
Subject: [PATCH] Define face for key bindings

It inherits from font-lock-constant-face to remain backward-compatible
with the previous style.
---
 pass.el | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/pass.el b/pass.el
index c405550..8e4bec9 100644
--- a/pass.el
+++ b/pass.el
@@ -87,6 +87,10 @@ (defface pass-mode-header-face '((t . (:inherit font-lock-keyword-face)))
   "Face for displaying the header of the pass buffer."
   :group 'pass)
 
+(defface pass-mode-keybinding-face '((t :inherit font-lock-constant-face))
+  "Face for displaying pass key bindings."
+  :group 'pass)
+
 (defface pass-mode-entry-face '((t . ()))
   "Face for displaying pass entry names."
   :group 'pass)
@@ -400,7 +404,7 @@ (defun pass--display-keybinding (command label)
                   (format "%s"
                           (propertize (substitute-command-keys
                                        (format "<\\[%s]>" (symbol-name command)))
-                                      'face 'font-lock-constant-face))
+                                      'face 'pass-mode-keybinding-face))
                   label)))
 
 (defun pass-display-item (item &optional indent-level)
-- 
2.35.1

```

**Comment by doolio** [comment]
@DamienCassou I think this could be easily merged.

**Comment by doolio** [comment]
OK, @protesilaos how would you like to proceed? I can submit the PR with your patch if you prefer.

**Comment by doolio** [comment]
I hope it is okay but I went ahead and submitted a PR for this as it allowed me to learn how to work with patches in `magit`. I believe I applied it correctly maintaining the metadata from @protesilaos such as author name and date.

**Comment by protesilaos** [comment]
> From: doolio ***@***.***>
> Date: Mon, 27 Nov 2023 10:26:41 -0800
>
> I hope it is okay but I went ahead and submitted a PR for this as it
> allowed me to learn how to work with patches in `magit`. I believe I
> applied it correctly maintaining the metadata from @protesilaos such
> as author name and date.

Sorry, I could not reply earlier. Yes, it's all good. Do as you see fit.
No worries!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by DamienCassou** [comment]
Thank you @protesilaos for the original patch and thank you @doolio for creating a PR and adding the face to the OTP support.
