### ISSUE TITLE
pass-quit should kill opened password buffers

### ISSUE THREAD

**Issue by bricewge** [NicolasPetton/pass#9]
There should at least be an option to kill all password's buffer when calling `pass-quit`. At the moment when you open a password and quit `pass` the buffer with the password in clear persist which is misleading since the user can think she had closed her password store.

**Comment by NicolasPetton** [comment]
Commit 6e5f557 fixed this issue:

- When closing the store (`q`, `pass-quit`), all password buffers can be closed
- When displaying an entry buffer, a new major mode is used, which hides the password by default (use `C-c C-c` to toggle this)
